### ISSUE TITLE
Module parse failed: Unexpected section: 0xc

### ISSUE THREAD

**Issue by Uzay-G** [xtuc/webassemblyjs#1092]
Related: https://github.com/webpack/webpack/issues/14087

When building my functional wasm package, I get:

```
Hash: 964659855f4448e72a10
Version: webpack 4.42.0
Time: 807ms
Built at: 05/15/2022 8:16:20 PM
 2 assets
Entrypoint index = index.js
[0] ./js/index.js 47 bytes {0} [built]
[1] ./pkg/index.js 97 bytes {1} [built]
[2] ./pkg/index_bg.js 21.4 KiB {1} [built]
[3] ./pkg/index_bg.wasm 1.86 KiB {1} [built] [failed] [1 error]
[4] (webpack)/buildin/harmony-module.js 573 bytes {1} [built]
[5] (webpack)/buildin/global.js 472 bytes {1} [built]

ERROR in ./pkg/index_bg.wasm
Module parse failed: Unexpected section: 0xc
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
Error: Unexpected section: 0xc
    at new CompileError (/home/halcyon/Documents/Projects/hora-wasm/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/home/halcyon/Documents/Projects/hora-wasm/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1678:11)
    at Object.decode (/home/halcyon/Documents/Projects/hora-wasm/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1696:25)
    at decode (/home/halcyon/Documents/Projects/hora-wasm/node_modules/@webassemblyjs/wasm-parser/lib/index.js:248:21)
    at WebAssemblyParser.parse (/home/halcyon/Documents/Projects/hora-wasm/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at /home/halcyon/Documents/Projects/hora-wasm/node_modules/webpack/lib/NormalModule.js:482:32
    at /home/halcyon/Documents/Projects/hora-wasm/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/halcyon/Documents/Projects/hora-wasm/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/halcyon/Documents/Projects/hora-wasm/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/halcyon/Documents/Projects/hora-wasm/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/halcyon/Documents/Projects/hora-wasm/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/halcyon/Documents/Projects/hora-wasm/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/halcyon/Documents/Projects/hora-wasm/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./pkg/index.js 1:0-40 3:0-21
 @ ./js/index.js

ERROR in chunk 1
6fbbd28fd493aeebb54a.module.wasm
/home/halcyon/Documents/Projects/hora-wasm/pkg/index_bg.wasm
unexpected end

```
How can I trouble-shoot / fix this?

**Comment by gustavohenke** [comment]
#918 seems to provide some useful steps

**Comment by Feel-ix-343** [comment]
This issue has come up for me with webpack 5.70   

3hrs of debugging later I figured out that webpack version 5.66 works
