### ISSUE TITLE
wast parser fails with function imports that have type references

### ISSUE THREAD

**Issue by ColinEberhardt** [xtuc/webassemblyjs#412]
Discovered while exploring #406 

The following fails:

```
(type (func (param i32)))
(import "module" "name" (func $name (type 0)))
```

With the following:

```
  Error:
  (type (func (param i32)))
  (import "module" "name" (func $name (type 0)))
                                      ^^^^


  Unexpected token in import of type, given keyword (type)
      at packages/wast-parser/lib/grammar.js:428:22
      at parseImport (packages/wast-parser/lib/grammar.js:429:14)
      at walk (packages/wast-parser/lib/grammar.js:1632:22)
      at Object.parse (packages/wast-parser/lib/grammar.js:1763:15)
      at parse (packages/wast-parser/lib/index.js:18:20)
      at pre (packages/wast-parser/test/index.js:24:21)
      at Context.<anonymous> (packages/helper-test-framework/lib/index.js:81:18)
```

I'll have a look at fixing this.

**Comment by void4** [comment]
Same problem here:

```

(module
  (type (func))
  (type  (func (param i32)))
  (import "metering" "usegas" (func (type 1)))
  (func (type 0)
    i32.const 92
    call 0
    nop)
  (export "add" (func 1)))

```

fails with:

```

Error: 
(module
  (type (func))
  (type  (func (param i32)))
  (import "metering" "usegas" (func (type 1)))
                                    ^^^^
  (func (type 0)
    i32.const 92
    call 0
    nop)
  (export "add" (func 1)))

Unexpected token in import of type, given keyword (type)
```

When compiled with wabt, then instantiated with webassemblyjs.instantiate, it fails with:


`Error: unknown function`

Looking closer into the source, it appears that imported functions do not seem to be initialized before declared functions. This is the initialized func array: `Array [ "func_1" ]` - the index of 1 returns undefined, which raises the "unknown function" exception.
