### ISSUE TITLE
Integrate TimHambourger/webassemblyjs-wasm-corruption test suite

### ISSUE THREAD

**Issue by xtuc** [xtuc/webassemblyjs#419]
@TimHambourger made a very useful test harness, we could integrate it in our CI somehow (if @TimHambourger is ok with that).

Note we can keep a seperated repo.

**Comment by TimHambourger** [comment]
@xtuc Yes! I'm certainly ok with this.

I'm curious how you're imagining this. My first thought would be to make it part of the core repo such that it runs on `make test` and picks up the local versions of each package. Does Lerna have a notion of a non-publishing package or some such?

Also, thinking through things I like about the current harness:
- It's geared towards "real" input files from multiple sources. I could see gradually expanding that list, as well as the list of transforms.
- It walks through a full cycle of parse, edit, re-parse.
- It's pretty minimal: For each input + transform combo, it just cares whether the output is valid WASM or not. So it doesn't assert everything there is to know about the output, but it still can catch byte counting errors etc. that are likely to produce corrupt output.

I don't have a clear point here. Just figured stating those might help define how this harness can fit within the  rest of the test suite.

**Comment by xtuc** [comment]
I would like to avoid adding more wasm binary into this repo and slow down current tests.

I can see two solutions:
- we could keep your repository (with a few structural changes), pull it from the CI and run it against the latest version of each packages.
- or a smoke testing approach, setup a cron in Travis and pull the latest version from npm of each packages.

FYI you can set `private: true` in the package.json to avoid Lerna to publish them.

**Comment by TimHambourger** [comment]
Yes, point well taken about not wanting to slow down current tests. Sure, I'm happy to keep this in my current repository, though I'd want to add you (and others as appropriate) as collaborators. I just don't want to become a bottleneck to changes getting approved.

**Comment by xtuc** [comment]
FYI, using `v1.6.0` your test suite had only a couple of fails but since `v1.7.0` it doesn't decode anymore.

```
/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/wasm-opt/lib/index.js:48
    throw new OptimizerError("shrinkPaddedLEB128", e);
    ^
Error: Unexpected section: 0x77
    at new CompileError (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1530:11)
    at Object.decode (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1547:25)
    at decode (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at shrinkPaddedLEB128 (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/node_modules/@webassemblyjs/wasm-opt/lib/index.js:45:38)
    at preprocess (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/index.js:142:20)
    at inputFiles.map.name (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/index.js:39:18)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/TimHambourger/webassemblyjs-wasm-corruption/webassemblyjs-repro/index.js:33:6)
    at Module._compile (module.js:660:30)
```

The diff is pretty noisy https://github.com/xtuc/webassemblyjs/compare/v1.6.0...v1.7.0, sorry.
