### ISSUE TITLE
How can I bundle the webassembly.js build into a single .js file?

### ISSUE THREAD

**Issue by void4** [xtuc/webassemblyjs#432]
I want to experiment with the interpreter a bit, but haven't figured out how I can get from `make build` to a single file, as is available here:
https://bundle.run/webassemblyjs@1.0.0-y.8
Can you show me?

**Comment by xtuc** [comment]
https://bundle.run is running Rollup/Browserify under the hood (which are bundlers) but we don't have a bundler setup here.

Are you targeting a browser or could you use the project using the Node API? Otherwise you'll need to setup a bundler.

**Comment by void4** [comment]
I'm targeting browsers. I have close to no experience with javascript, can you recommend one? Webpack or Browserify maybe?

**Comment by xtuc** [comment]
Webpack or Browserify are both fine.

We use Babel to transpile out the type annotation (and some other syntaxes), see https://github.com/xtuc/webassemblyjs/blob/master/.babelrc.js#L11.

Also you'll need to inlude a Buffer polyfill, see https://github.com/xtuc/webassemblyjs#nodes-buffer.

**Comment by void4** [comment]
Okay, so I install babel globally:
`npm install -g babel-cli`

copied `.babelrc.js` into `packages/webassemblyjs/src/` and renamed it `.babelrc`

```
SyntaxError: /home/void/webassemblyjs/packages/webassemblyjs/src/.babelrc: Error while parsing JSON - Unexpected 'c' at line 1 column 2 of the JSON5 data. Still to read: "const useESM = proce"
    at error (/usr/local/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:56:25)
    at word (/usr/local/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:393:13)
    at value (/usr/local/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:493:56)
    at Object.parse (/usr/local/lib/node_modules/babel-cli/node_modules/json5/lib/json5.js:508:18)
    at ConfigChainBuilder.addConfig (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:150:65)
    at ConfigChainBuilder.findConfigs (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
    at buildConfigChain (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
    at OptionManager.init (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
    at File.initOptions (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/usr/local/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:135:24)
```

**Comment by xtuc** [comment]
Sorry I can not help you with that, it's out of the scope of the project.

**Comment by void4** [comment]
I managed to transpile and bundle the files.

```
#In packages/webassemblyjs/

# Install dependencies
npm install .

# Install latest babel (only that supports babelrc.js)
npm install --save-dev @babel/core @babel/cli @babel/preset-env
npm install @babel/preset-env @babel/preset-flow @babel/plugin-proposal-export-default-from @babel/plugin-proposal-object-rest-spread babel-plugin-mamacro

# Transpile all source files to lib/
./node_modules/.bin/babel src --out-dir lib 
# Successfully compiled 27 files with Babel.

# In lib/, Bundle all files into a single bundle.js
browserify . > bundle.js
```

The script seems to load fine, but I don't know what it exports yet.
```<script src="bundle.js"></script>```
