### ISSUE TITLE
"unknown import", multiple arguments to imported function

### ISSUE THREAD

**Issue by void4** [xtuc/webassemblyjs#435]
When trying to import these functions:

```javascript
<script src="webassemblyjs@1.0.0-y.8.js"></script>
<!--<script src="bundle.js"></script>-->

<script>
var code = `
(module
  (import "canvas" "draw" (func $0  (param i32 i32)))
  (import "metering" "usegas" (func $1  (param i32)))
  (func $2
    (i32.const 183)
    (call $1)
    (i32.const 150)
    (i32.const 150)
    (call $0)
  )
  (export "custom" (func $2))
)
`

function draw(a,b) {
    console.log(a,b)
}

function usegas(i) {
    console.log(i)
}

var IO = {"canvas":{draw}, "metering":{usegas}}

var instance = webassemblyjs.instantiateFromSource(code, IO);
try {
    var res = instance.exports.custom();
    console.log(res)
} catch (e) {
    console.log("Exception:", e)
}
</script>

```

webassemblyjs fails with:
```javascript
Error: Unknown import canvas.0 webassemblyjs@1.0.0-y.8.js:394:46
CompileError
webassemblyjs@1.0.0-y.8.js:394:46 getExternalElementOrThrow
webassemblyjs@1.0.0-y.8.js:3588:13 handleFuncImport
webassemblyjs@1.0.0-y.8.js:3595:19 instantiateImports/<.ModuleImport<
webassemblyjs@1.0.0-y.8.js:3657:18 ModuleImport
webassemblyjs@1.0.0-y.8.js:3643:16 traverse/<
webassemblyjs@1.0.0-y.8.js:5704:7 walk
webassemblyjs@1.0.0-y.8.js:5582:5 walk/<
webassemblyjs@1.0.0-y.8.js:5558:16 forEach self-hosted:268:13 walk
webassemblyjs@1.0.0-y.8.js:5557:7 traverse
webassemblyjs@1.0.0-y.8.js:5702:3 instantiateImports
webassemblyjs@1.0.0-y.8.js:3640:4 createInstance
webassemblyjs@1.0.0-y.8.js:4067:3 Instance
webassemblyjs@1.0.0-y.8.js:747:26 instantiateFromSource
webassemblyjs@1.0.0-y.8.js:477:12 <anonymous>

```

I'm not sure why that is. I've tried giving it a different name ("$a"), but with the same result.

I'm also not sure how and if I should rewrite the multiple arguments to the imported function, since you mentioned it doesn't fully support the stack syntax. I suppose it should be something like `(call $0 (i32.const 150) (i32.const 150))`, but that hasn't worked.

**Comment by xtuc** [comment]
It seems that you are using an old version of the project. https://github.com/xtuc/webassemblyjs/releases/tag/v1.0.0-y.8 was released almost one year ago.

On master, it throws a validation error:
```
xtuc/webassemblyjs/packages/validation/lib/index.js:46
    throw new Error(errorMessage);
    ^
Error: Validation errors:
Expected type i32 but got none.
    at validateAST (xtuc/webassemblyjs/packages/validation/lib/index.js:46:11)
    at createCompiledModule (xtuc/webassemblyjs/packages/webassemblyjs/lib/compiler/compile/module.js:43:27)
    at Object.instantiateFromSource (xtuc/webassemblyjs/packages/webassemblyjs/lib/index.js:59:18)
    at Object.<anonymous> (/tmp/test/index.js:27:30)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
``` 

I'm working on it.

**Comment by xtuc** [comment]
FYI PR is here https://github.com/xtuc/webassemblyjs/pull/436 but it seems that I broke some stuff

**Comment by void4** [comment]
Awesome, thank you!
