### ISSUE TITLE
wast-refmt and wast-to-wasm-semantics fail with unknown type: Memory

### ISSUE THREAD

**Issue by Ekleog** [xtuc/webassemblyjs#441]
Running wast-refmt or wast-to-wasm-semantics on the following `.wat` file:
```
(module
  (type $0 (func (param i32) (result i32)))
  (table $0 1 1 anyfunc)
  (memory $0 16)
  (global $0 i32 (i32.const 1048576))
  (global $1 i32 (i32.const 1048576))
  (func $0
    (type 0)
    (get_local 0)
    (i32.const 1)
    (i32.add)
    (i32.const 65535)
    (i32.and)
  )
  (func $1
    (type 0)
    (get_local 0)
    (i32.const 1)
    (i32.add)
    (i32.const 65535)
    (i32.and)
    (call 0)
  )
  (export "memory" (memory 0))
  (export "__heap_base" (global 0))
  (export "__data_end" (global 1))
  (export "test" (func 0))
  (export "hello_world" (func 1))
)
```

Fails with:
```
/[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:849
    throw new Error("printModuleExport: unknown type: " + n.descr.exportType);
    ^

Error: printModuleExport: unknown type: Memory
    at printModuleExport (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:849:11)
    at /[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:148:18
    at Array.forEach (native)
    at printModule (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:116:12)
    at /[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:43:14
    at Array.reduce (native)
    at printProgram (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:41:17)
    at print (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/node_modules/@webassemblyjs/wast-printer/lib/index.js:34:12)
    at _default (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/lib/index.js:14:33)
    at Object.<anonymous> (/[…]/lib/node_modules/@webassemblyjs/wast-refmt/lib/cli.js:16:18)
```

**Comment by Ekleog** [comment]
Thank you! :)
