### ISSUE TITLE
Bug: cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by yevgenypats** [xtuc/webassemblyjs#669]
Hey,

Found the following bug that can be reproduced with:

```javascript
const wast = require("@webassemblyjs/wast-parser");
wast.parse('"\u0019g ')

Thrown:
TypeError: Cannot read property 'charCodeAt' of undefined
    at isNewLine (/Users/yevgenyp/fuzzitdev/jsfuzz/node_modules/@webassemblyjs/wast-parser/lib/tokenizer.js:33:15)
    at tokenize (/Users/yevgenyp/fuzzitdev/jsfuzz/node_modules/@webassemblyjs/wast-parser/lib/tokenizer.js:347:13)
    at Object.parse (/Users/yevgenyp/fuzzitdev/jsfuzz/node_modules/@webassemblyjs/wast-parser/lib/index.js:31:40)

```

Found using [jsfuzz](https://github.com/fuzzitdev/jsfuzz)

**Comment by xtuc** [comment]
Would you mind sending a PR?

**Comment by yevgenypats** [comment]
hey @xtuc !:) I'm not sure I'll have time in the near future but I suggest marking this as bug/help wanted and maybe someone will be able to contribute the PR before me.
